// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/lili/proto/pb/CoachLogin.proto

package com.lili.proto.java;

public final class CoachLoginProto {
  private CoachLoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CoachLoginMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string token = 1;
    /**
     * <code>required string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    // required string phoneNum = 2;
    /**
     * <code>required string phoneNum = 2;</code>
     */
    boolean hasPhoneNum();
    /**
     * <code>required string phoneNum = 2;</code>
     */
    java.lang.String getPhoneNum();
    /**
     * <code>required string phoneNum = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumBytes();

    // required int64 coachId = 3;
    /**
     * <code>required int64 coachId = 3;</code>
     */
    boolean hasCoachId();
    /**
     * <code>required int64 coachId = 3;</code>
     */
    long getCoachId();
  }
  /**
   * Protobuf type {@code com.lili.proto.pb.CoachLoginMsg}
   */
  public static final class CoachLoginMsg extends
      com.google.protobuf.GeneratedMessage
      implements CoachLoginMsgOrBuilder {
    // Use CoachLoginMsg.newBuilder() to construct.
    private CoachLoginMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CoachLoginMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CoachLoginMsg defaultInstance;
    public static CoachLoginMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CoachLoginMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CoachLoginMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              phoneNum_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              coachId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lili.proto.java.CoachLoginProto.CoachLoginMsg.class, com.lili.proto.java.CoachLoginProto.CoachLoginMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CoachLoginMsg> PARSER =
        new com.google.protobuf.AbstractParser<CoachLoginMsg>() {
      public CoachLoginMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CoachLoginMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CoachLoginMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>required string token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string phoneNum = 2;
    public static final int PHONENUM_FIELD_NUMBER = 2;
    private java.lang.Object phoneNum_;
    /**
     * <code>required string phoneNum = 2;</code>
     */
    public boolean hasPhoneNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string phoneNum = 2;</code>
     */
    public java.lang.String getPhoneNum() {
      java.lang.Object ref = phoneNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phoneNum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string phoneNum = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumBytes() {
      java.lang.Object ref = phoneNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 coachId = 3;
    public static final int COACHID_FIELD_NUMBER = 3;
    private long coachId_;
    /**
     * <code>required int64 coachId = 3;</code>
     */
    public boolean hasCoachId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 coachId = 3;</code>
     */
    public long getCoachId() {
      return coachId_;
    }

    private void initFields() {
      token_ = "";
      phoneNum_ = "";
      coachId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhoneNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCoachId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPhoneNumBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, coachId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPhoneNumBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, coachId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lili.proto.java.CoachLoginProto.CoachLoginMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lili.proto.pb.CoachLoginMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lili.proto.java.CoachLoginProto.CoachLoginMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lili.proto.java.CoachLoginProto.CoachLoginMsg.class, com.lili.proto.java.CoachLoginProto.CoachLoginMsg.Builder.class);
      }

      // Construct using com.lili.proto.java.CoachLoginProto.CoachLoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        phoneNum_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        coachId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginMsg_descriptor;
      }

      public com.lili.proto.java.CoachLoginProto.CoachLoginMsg getDefaultInstanceForType() {
        return com.lili.proto.java.CoachLoginProto.CoachLoginMsg.getDefaultInstance();
      }

      public com.lili.proto.java.CoachLoginProto.CoachLoginMsg build() {
        com.lili.proto.java.CoachLoginProto.CoachLoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lili.proto.java.CoachLoginProto.CoachLoginMsg buildPartial() {
        com.lili.proto.java.CoachLoginProto.CoachLoginMsg result = new com.lili.proto.java.CoachLoginProto.CoachLoginMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.phoneNum_ = phoneNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.coachId_ = coachId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lili.proto.java.CoachLoginProto.CoachLoginMsg) {
          return mergeFrom((com.lili.proto.java.CoachLoginProto.CoachLoginMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lili.proto.java.CoachLoginProto.CoachLoginMsg other) {
        if (other == com.lili.proto.java.CoachLoginProto.CoachLoginMsg.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasPhoneNum()) {
          bitField0_ |= 0x00000002;
          phoneNum_ = other.phoneNum_;
          onChanged();
        }
        if (other.hasCoachId()) {
          setCoachId(other.getCoachId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToken()) {
          
          return false;
        }
        if (!hasPhoneNum()) {
          
          return false;
        }
        if (!hasCoachId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lili.proto.java.CoachLoginProto.CoachLoginMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lili.proto.java.CoachLoginProto.CoachLoginMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string token = 1;
      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      // required string phoneNum = 2;
      private java.lang.Object phoneNum_ = "";
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public boolean hasPhoneNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public java.lang.String getPhoneNum() {
        java.lang.Object ref = phoneNum_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          phoneNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumBytes() {
        java.lang.Object ref = phoneNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public Builder setPhoneNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        phoneNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public Builder clearPhoneNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        phoneNum_ = getDefaultInstance().getPhoneNum();
        onChanged();
        return this;
      }
      /**
       * <code>required string phoneNum = 2;</code>
       */
      public Builder setPhoneNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        phoneNum_ = value;
        onChanged();
        return this;
      }

      // required int64 coachId = 3;
      private long coachId_ ;
      /**
       * <code>required int64 coachId = 3;</code>
       */
      public boolean hasCoachId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 coachId = 3;</code>
       */
      public long getCoachId() {
        return coachId_;
      }
      /**
       * <code>required int64 coachId = 3;</code>
       */
      public Builder setCoachId(long value) {
        bitField0_ |= 0x00000004;
        coachId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 coachId = 3;</code>
       */
      public Builder clearCoachId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        coachId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lili.proto.pb.CoachLoginMsg)
    }

    static {
      defaultInstance = new CoachLoginMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lili.proto.pb.CoachLoginMsg)
  }

  public interface CoachLoginAckMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isSuccess = 1;
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    boolean getIsSuccess();
  }
  /**
   * Protobuf type {@code com.lili.proto.pb.CoachLoginAckMsg}
   */
  public static final class CoachLoginAckMsg extends
      com.google.protobuf.GeneratedMessage
      implements CoachLoginAckMsgOrBuilder {
    // Use CoachLoginAckMsg.newBuilder() to construct.
    private CoachLoginAckMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CoachLoginAckMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CoachLoginAckMsg defaultInstance;
    public static CoachLoginAckMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CoachLoginAckMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CoachLoginAckMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSuccess_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginAckMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginAckMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg.class, com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CoachLoginAckMsg> PARSER =
        new com.google.protobuf.AbstractParser<CoachLoginAckMsg>() {
      public CoachLoginAckMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CoachLoginAckMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CoachLoginAckMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool isSuccess = 1;
    public static final int ISSUCCESS_FIELD_NUMBER = 1;
    private boolean isSuccess_;
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    private void initFields() {
      isSuccess_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSuccess_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuccess_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lili.proto.pb.CoachLoginAckMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lili.proto.java.CoachLoginProto.CoachLoginAckMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginAckMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginAckMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg.class, com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg.Builder.class);
      }

      // Construct using com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lili.proto.java.CoachLoginProto.internal_static_com_lili_proto_pb_CoachLoginAckMsg_descriptor;
      }

      public com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg getDefaultInstanceForType() {
        return com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg.getDefaultInstance();
      }

      public com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg build() {
        com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg buildPartial() {
        com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg result = new com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSuccess_ = isSuccess_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg) {
          return mergeFrom((com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg other) {
        if (other == com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg.getDefaultInstance()) return this;
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lili.proto.java.CoachLoginProto.CoachLoginAckMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isSuccess = 1;
      private boolean isSuccess_ ;
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lili.proto.pb.CoachLoginAckMsg)
    }

    static {
      defaultInstance = new CoachLoginAckMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lili.proto.pb.CoachLoginAckMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lili_proto_pb_CoachLoginMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lili_proto_pb_CoachLoginMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lili_proto_pb_CoachLoginAckMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lili_proto_pb_CoachLoginAckMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,main/java/com/lili/proto/pb/CoachLogin" +
      ".proto\022\021com.lili.proto.pb\"A\n\rCoachLoginM" +
      "sg\022\r\n\005token\030\001 \002(\t\022\020\n\010phoneNum\030\002 \002(\t\022\017\n\007c" +
      "oachId\030\003 \002(\003\"%\n\020CoachLoginAckMsg\022\021\n\tisSu" +
      "ccess\030\001 \002(\010B&\n\023com.lili.proto.javaB\017Coac" +
      "hLoginProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lili_proto_pb_CoachLoginMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lili_proto_pb_CoachLoginMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lili_proto_pb_CoachLoginMsg_descriptor,
              new java.lang.String[] { "Token", "PhoneNum", "CoachId", });
          internal_static_com_lili_proto_pb_CoachLoginAckMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_lili_proto_pb_CoachLoginAckMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lili_proto_pb_CoachLoginAckMsg_descriptor,
              new java.lang.String[] { "IsSuccess", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
