// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/lili/proto/pb/CoachReport.proto

#ifndef PROTOBUF_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto__INCLUDED
#define PROTOBUF_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace lili {
namespace proto {
namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto();
void protobuf_AssignDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto();
void protobuf_ShutdownFile_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto();

class CoachReportMsg;

// ===================================================================

class CoachReportMsg : public ::google::protobuf::Message {
 public:
  CoachReportMsg();
  virtual ~CoachReportMsg();

  CoachReportMsg(const CoachReportMsg& from);

  inline CoachReportMsg& operator=(const CoachReportMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CoachReportMsg& default_instance();

  void Swap(CoachReportMsg* other);

  // implements Message ----------------------------------------------

  CoachReportMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CoachReportMsg& from);
  void MergeFrom(const CoachReportMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double lge = 1;
  inline bool has_lge() const;
  inline void clear_lge();
  static const int kLgeFieldNumber = 1;
  inline double lge() const;
  inline void set_lge(double value);

  // required double lae = 2;
  inline bool has_lae() const;
  inline void clear_lae();
  static const int kLaeFieldNumber = 2;
  inline double lae() const;
  inline void set_lae(double value);

  // required float dir = 3;
  inline bool has_dir() const;
  inline void clear_dir();
  static const int kDirFieldNumber = 3;
  inline float dir() const;
  inline void set_dir(float value);

  // @@protoc_insertion_point(class_scope:com.lili.proto.pb.CoachReportMsg)
 private:
  inline void set_has_lge();
  inline void clear_has_lge();
  inline void set_has_lae();
  inline void clear_has_lae();
  inline void set_has_dir();
  inline void clear_has_dir();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double lge_;
  double lae_;
  float dir_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto();
  friend void protobuf_AssignDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto();
  friend void protobuf_ShutdownFile_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto();

  void InitAsDefaultInstance();
  static CoachReportMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// CoachReportMsg

// required double lge = 1;
inline bool CoachReportMsg::has_lge() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CoachReportMsg::set_has_lge() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CoachReportMsg::clear_has_lge() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CoachReportMsg::clear_lge() {
  lge_ = 0;
  clear_has_lge();
}
inline double CoachReportMsg::lge() const {
  return lge_;
}
inline void CoachReportMsg::set_lge(double value) {
  set_has_lge();
  lge_ = value;
}

// required double lae = 2;
inline bool CoachReportMsg::has_lae() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CoachReportMsg::set_has_lae() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CoachReportMsg::clear_has_lae() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CoachReportMsg::clear_lae() {
  lae_ = 0;
  clear_has_lae();
}
inline double CoachReportMsg::lae() const {
  return lae_;
}
inline void CoachReportMsg::set_lae(double value) {
  set_has_lae();
  lae_ = value;
}

// required float dir = 3;
inline bool CoachReportMsg::has_dir() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CoachReportMsg::set_has_dir() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CoachReportMsg::clear_has_dir() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CoachReportMsg::clear_dir() {
  dir_ = 0;
  clear_has_dir();
}
inline float CoachReportMsg::dir() const {
  return dir_;
}
inline void CoachReportMsg::set_dir(float value) {
  set_has_dir();
  dir_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace proto
}  // namespace lili
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_main_2fjava_2fcom_2flili_2fproto_2fpb_2fCoachReport_2eproto__INCLUDED
