// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/lili/proto/pb/Ping.proto

#ifndef PROTOBUF_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto__INCLUDED
#define PROTOBUF_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace lili {
namespace proto {
namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();
void protobuf_AssignDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();
void protobuf_ShutdownFile_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();

class PingMsg;
class PongMsg;

// ===================================================================

class PingMsg : public ::google::protobuf::Message {
 public:
  PingMsg();
  virtual ~PingMsg();

  PingMsg(const PingMsg& from);

  inline PingMsg& operator=(const PingMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PingMsg& default_instance();

  void Swap(PingMsg* other);

  // implements Message ----------------------------------------------

  PingMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PingMsg& from);
  void MergeFrom(const PingMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 clientTimestamp = 1;
  inline bool has_clienttimestamp() const;
  inline void clear_clienttimestamp();
  static const int kClientTimestampFieldNumber = 1;
  inline ::google::protobuf::int64 clienttimestamp() const;
  inline void set_clienttimestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:com.lili.proto.pb.PingMsg)
 private:
  inline void set_has_clienttimestamp();
  inline void clear_has_clienttimestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 clienttimestamp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();
  friend void protobuf_AssignDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();
  friend void protobuf_ShutdownFile_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();

  void InitAsDefaultInstance();
  static PingMsg* default_instance_;
};
// -------------------------------------------------------------------

class PongMsg : public ::google::protobuf::Message {
 public:
  PongMsg();
  virtual ~PongMsg();

  PongMsg(const PongMsg& from);

  inline PongMsg& operator=(const PongMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PongMsg& default_instance();

  void Swap(PongMsg* other);

  // implements Message ----------------------------------------------

  PongMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PongMsg& from);
  void MergeFrom(const PongMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 clientTimestamp = 1;
  inline bool has_clienttimestamp() const;
  inline void clear_clienttimestamp();
  static const int kClientTimestampFieldNumber = 1;
  inline ::google::protobuf::int64 clienttimestamp() const;
  inline void set_clienttimestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:com.lili.proto.pb.PongMsg)
 private:
  inline void set_has_clienttimestamp();
  inline void clear_has_clienttimestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 clienttimestamp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();
  friend void protobuf_AssignDesc_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();
  friend void protobuf_ShutdownFile_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto();

  void InitAsDefaultInstance();
  static PongMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// PingMsg

// required int64 clientTimestamp = 1;
inline bool PingMsg::has_clienttimestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PingMsg::set_has_clienttimestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PingMsg::clear_has_clienttimestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PingMsg::clear_clienttimestamp() {
  clienttimestamp_ = GOOGLE_LONGLONG(0);
  clear_has_clienttimestamp();
}
inline ::google::protobuf::int64 PingMsg::clienttimestamp() const {
  return clienttimestamp_;
}
inline void PingMsg::set_clienttimestamp(::google::protobuf::int64 value) {
  set_has_clienttimestamp();
  clienttimestamp_ = value;
}

// -------------------------------------------------------------------

// PongMsg

// required int64 clientTimestamp = 1;
inline bool PongMsg::has_clienttimestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PongMsg::set_has_clienttimestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PongMsg::clear_has_clienttimestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PongMsg::clear_clienttimestamp() {
  clienttimestamp_ = GOOGLE_LONGLONG(0);
  clear_has_clienttimestamp();
}
inline ::google::protobuf::int64 PongMsg::clienttimestamp() const {
  return clienttimestamp_;
}
inline void PongMsg::set_clienttimestamp(::google::protobuf::int64 value) {
  set_has_clienttimestamp();
  clienttimestamp_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace proto
}  // namespace lili
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_main_2fjava_2fcom_2flili_2fproto_2fpb_2fPing_2eproto__INCLUDED
