package com.lili.order.dao.mapper;

import java.util.List;
import java.util.Date;
import com.lili.order.dao.po.CoachClassPo;

public interface CoachClassMapper{

  public void addCoachClass(CoachClassPo coachclassPo);
  public void addCoachClassList(List<CoachClassPo> coachclassPoList);
  public void delCoachClassById(Integer ccid);
  public void delCoachClassByIds(List<Integer> ids);
  public void delCoachClassByObj(CoachClassPo coachclassPo);
  public void saveCoachClass(CoachClassPo coachclassPo);
  public void saveCoachClassList(List<CoachClassPo> coachclassPoList);
  public int updateByCcid(CoachClassPo coachclassPo,Integer ccid);
  public int updateByCtype(CoachClassPo coachclassPo,Integer ctype);
  public int updateByCoachId(CoachClassPo coachclassPo,Long coachId);
  public int updateByCstart(CoachClassPo coachclassPo,Date cstart);
  public int updateByCend(CoachClassPo coachclassPo,Date cend);
  public int updateByRstart(CoachClassPo coachclassPo,Date rstart);
  public int updateByRend(CoachClassPo coachclassPo,Date rend);
  public int updateByOrderId(CoachClassPo coachclassPo,String orderId);
  public int updateByMaxNum(CoachClassPo coachclassPo,Integer maxNum);
  public int updateByBookNum(CoachClassPo coachclassPo,Integer bookNum);
  public int updateByCarId(CoachClassPo coachclassPo,Integer carId);
  public int updateByCarName(CoachClassPo coachclassPo,String carName);
  public int updateByCarImg(CoachClassPo coachclassPo,String carImg);
  public int updateByCarNo(CoachClassPo coachclassPo,String carNo);
  public int updateByCourseId(CoachClassPo coachclassPo,String courseId);
  public int updateByCourseName(CoachClassPo coachclassPo,String courseName);
  public int updateByPlaceId(CoachClassPo coachclassPo,Integer placeId);
  public int updateByPlaceName(CoachClassPo coachclassPo,String placeName);
  public int updateByPrice(CoachClassPo coachclassPo,Integer price);
  public int updateByDltype(CoachClassPo coachclassPo,Integer dltype);
  public int updateByTid(CoachClassPo coachclassPo,Integer tid);
  public int updateByIsdel(CoachClassPo coachclassPo,Integer isdel);
  public int updateNotNullByObject(CoachClassPo coachclassPo,CoachClassPo search);
  public int updateAllByObject(CoachClassPo coachclassPo,CoachClassPo search);
  public CoachClassPo queryCoachClassById(Integer ccid,String postSql,String queryFields);
  public List<CoachClassPo> queryCoachClassByIds(List<Integer> ids,String postSql,String queryFields);
  public List<CoachClassPo> queryByObjectAnd(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByObjectOr(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByCcid(Integer ccid,String postSql,String queryFields);
  public List<CoachClassPo> queryByCtype(Integer ctype,String postSql,String queryFields);
  public List<CoachClassPo> queryByCoachId(Long coachId,String postSql,String queryFields);
  public List<CoachClassPo> queryByCstart(Date cstart,String postSql,String queryFields);
  public List<CoachClassPo> queryByCend(Date cend,String postSql,String queryFields);
  public List<CoachClassPo> queryByRstart(Date rstart,String postSql,String queryFields);
  public List<CoachClassPo> queryByRend(Date rend,String postSql,String queryFields);
  public List<CoachClassPo> queryByOrderId(String orderId,String postSql,String queryFields);
  public List<CoachClassPo> queryByMaxNum(Integer maxNum,String postSql,String queryFields);
  public List<CoachClassPo> queryByBookNum(Integer bookNum,String postSql,String queryFields);
  public List<CoachClassPo> queryByCarId(Integer carId,String postSql,String queryFields);
  public List<CoachClassPo> queryByCarName(String carName,String postSql,String queryFields);
  public List<CoachClassPo> queryByCarImg(String carImg,String postSql,String queryFields);
  public List<CoachClassPo> queryByCarNo(String carNo,String postSql,String queryFields);
  public List<CoachClassPo> queryByCourseId(String courseId,String postSql,String queryFields);
  public List<CoachClassPo> queryByCourseName(String courseName,String postSql,String queryFields);
  public List<CoachClassPo> queryByPlaceId(Integer placeId,String postSql,String queryFields);
  public List<CoachClassPo> queryByPlaceName(String placeName,String postSql,String queryFields);
  public List<CoachClassPo> queryByPrice(Integer price,String postSql,String queryFields);
  public List<CoachClassPo> queryByDltype(Integer dltype,String postSql,String queryFields);
  public List<CoachClassPo> queryByTid(Integer tid,String postSql,String queryFields);
  public List<CoachClassPo> queryByIsdel(Integer isdel,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew0(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew1(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew2(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew3(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew4(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew5(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew6(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew7(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew8(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew9(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew10(CoachClassPo coachclassPo,String postSql,String queryFields);
  public List<CoachClassPo> queryByNew11(CoachClassPo coachclassPo,String postSql,String queryFields);
  public Integer queryBookNumByCoachId(Long coachId, String postSql, String sqlFileld);
  public Integer queryBookNumByCcId(Integer ccid, String postSql, String sqlFileld);
  public Integer queryBookNumByOrderId(String orderId, String postSql, String sqlFileld);
  public Integer queryBookNumByCoachId2(Long coachId, String postSql, String sqlFileld);

}
