ALTER TABLE t_coach_class ADD INDEX IDX_coachid_cstart (COACH_ID,CSTART);

ALTER TABLE t_order ADD INDEX IDX_STUDENT_ID_PAY_STATE (STUDENT_ID);
ALTER TABLE t_order ADD INDEX IDX_coach_order(coach_id,order_state,ccid);
-- ALTER TABLE t_order ADD INDEX IDX_OT_CO_CC (OTYPE,COACH_ID,CCID);


ALTER TABLE t_u_coach ADD INDEX IDX_SCHOOLID_COACHID (COACHID,SCHOOLID,NAME);
-- ALTER TABLE t_u_coach ADD INDEX IDX_NA_CO_SC (COACHID,SCHOOLID,NAME);

ALTER TABLE t_u_coachcar ADD INDEX IDX_COACHID_CARID (COACHID,CARID);
ALTER TABLE t_u_student ADD INDEX IDX_RE_NA_PH_IS (REGISTERTIME,NAME,PHONENUM);

