package com.lili.student.service;

import java.util.List;
import java.util.Date;
import com.lili.student.vo.VipCompanyQuery;
import com.lili.student.vo.VipCompanyVo;

public interface VipCompanyService {

  public void addVipCompany(VipCompanyVo vipCompanyvo)  throws Exception;
  public void addVipCompanyList(List<VipCompanyVo> vipCompanyvoList)  throws Exception;
  public void delVipCompanyById(Integer coid)  throws Exception;
  public void delVipCompanyByIds(List<Integer> ids)  throws Exception;
  public void delVipCompanyByObj(VipCompanyVo vipCompanyvo)  throws Exception;
  public void saveVipCompany(VipCompanyVo vipCompanyvo)  throws Exception;
  public void saveVipCompanyList(List<VipCompanyVo> vipCompanyvoList)  throws Exception;
  public int updateByCoid(VipCompanyVo vipCompanyvo,Integer coid)  throws Exception;
  public int updateByCompany(VipCompanyVo vipCompanyvo,String company)  throws Exception;
  public int updateByVtype(VipCompanyVo vipCompanyvo,Integer vtype)  throws Exception;
  public int updateByShorter(VipCompanyVo vipCompanyvo,String shorter)  throws Exception;
  public int updateByProvinceId(VipCompanyVo vipCompanyvo,Integer provinceId)  throws Exception;
  public int updateByCityId(VipCompanyVo vipCompanyvo,Integer cityId)  throws Exception;
  public int updateByProvince(VipCompanyVo vipCompanyvo,String province)  throws Exception;
  public int updateByCity(VipCompanyVo vipCompanyvo,String city)  throws Exception;
  public int updateByManger(VipCompanyVo vipCompanyvo,String manger)  throws Exception;
  public int updateByMobile(VipCompanyVo vipCompanyvo,String mobile)  throws Exception;
  public int updateByPhone(VipCompanyVo vipCompanyvo,String phone)  throws Exception;
  public int updateByEmail(VipCompanyVo vipCompanyvo,String email)  throws Exception;
  public int updateByRcid(VipCompanyVo vipCompanyvo,String rcid)  throws Exception;
  public int updateByRemark(VipCompanyVo vipCompanyvo,String remark)  throws Exception;
  public int updateByActive(VipCompanyVo vipCompanyvo,Integer active)  throws Exception;
  public int updateByAgreement(VipCompanyVo vipCompanyvo,String agreement)  throws Exception;
  public int updateByVstate(VipCompanyVo vipCompanyvo,Integer vstate)  throws Exception;
  public int updateByReason(VipCompanyVo vipCompanyvo,String reason)  throws Exception;
  public int updateByIsdel(VipCompanyVo vipCompanyvo,Integer isdel)  throws Exception;
  public int updateByCuid(VipCompanyVo vipCompanyvo,Long cuid)  throws Exception;
  public int updateByMuid(VipCompanyVo vipCompanyvo,Long muid)  throws Exception;
  public int updateByCtime(VipCompanyVo vipCompanyvo,Date ctime)  throws Exception;
  public int updateByMtime(VipCompanyVo vipCompanyvo,String mtime)  throws Exception;
  public int updateNotNullByObject(VipCompanyVo vipCompanyvo,VipCompanyVo search)  throws Exception;
  public int updateAllByObject(VipCompanyVo vipCompanyvo,VipCompanyVo search)  throws Exception;
  public VipCompanyVo queryVipCompanyById(Integer coid)  throws Exception;
  public List<VipCompanyVo> queryVipCompanyByIds(List<Integer> ids,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByObjectAnd(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public Integer countByObject(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByObjectOr(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByCoid(Integer coid,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByCompany(String company,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByVtype(Integer vtype,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByShorter(String shorter,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByProvinceId(Integer provinceId,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByCityId(Integer cityId,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByProvince(String province,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByCity(String city,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByManger(String manger,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByMobile(String mobile,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByPhone(String phone,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByEmail(String email,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByRcid(String rcid,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByRemark(String remark,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByActive(Integer active,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByAgreement(String agreement,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByVstate(Integer vstate,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByReason(String reason,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByIsdel(Integer isdel,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByCuid(Long cuid,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByMuid(Long muid,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByCtime(Date ctime,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByMtime(String mtime,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByNew0(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByNew1(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByNew2(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByNew3(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByNew4(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByNew5(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByNew6(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;
  public List<VipCompanyVo> queryByNew7(VipCompanyVo vipCompanyvo,VipCompanyQuery vipCompanyQuery)  throws Exception;

}
